rule:
	gcc -o HWL -s ./main.c ./root.c ./daemon.c ./loader.c ./worker.c ./render.c ./summary.c ./menu.c ./keyboard.c ./player.c ./map.c ./listener.c ./scheduler.c ./sounds.c ./data.c ./overlay.c ./hints.c ./scripts.c ./util.c -I/usr/include/allegro5 -L/usr/lib -lallegro -lm -lallegro_image -lallegro_ttf -lallegro_font -lallegro_audio -lallegro_primitives -lallegro_acodec

